games = [
    {"name": "The Witcher 3", "genres": ["RPG", "Aventura"], "platform": "PC"},
    {"name": "FIFA 24", "genres": ["Esporte"], "platform": "PS5"},
    {"name": "Elden Ring", "genres": ["RPG", "Ação", "Souls-like"], "platform": "Multi"},
    {"name": "God of War Ragnarök", "genres": ["Ação", "Aventura"], "platform": "PS5"},
    {"name": "Zelda: Tears of the Kingdom", "genres": ["Aventura", "RPG"], "platform": "Switch"},
    {"name": "Starfield", "genres": ["RPG", "Ficção Científica"], "platform": "PC/Xbox"},
    {"name": "Call of Duty: Modern Warfare III", "genres": ["FPS", "Ação"], "platform": "Multi"},
    {"name": "Minecraft", "genres": ["Sandbox", "Sobrevivência"], "platform": "Multi"},
    {"name": "Grand Theft Auto V", "genres": ["Ação", "Mundo Aberto"], "platform": "Multi"},
    {"name": "Red Dead Redemption 2", "genres": ["Aventura", "Oeste"], "platform": "Multi"},
    {"name": "Counter-Strike 2", "genres": ["FPS", "Tático"], "platform": "PC"},
    {"name": "League of Legends", "genres": ["MOBA", "Estratégia"], "platform": "PC"},
    {"name": "Valorant", "genres": ["FPS", "Tático"], "platform": "PC"},
    {"name": "Fortnite", "genres": ["Battle Royale", "Survival"], "platform": "Multi"},
    {"name": "Apex Legends", "genres": ["Battle Royale", "FPS"], "platform": "Multi"},
    {"name": "Cyberpunk 2077", "genres": ["RPG", "Cyberpunk"], "platform": "Multi"},
    {"name": "Baldur's Gate 3", "genres": ["RPG", "Estratégia", "Turno"], "platform": "Multi"},
    {"name": "Hogwarts Legacy", "genres": ["RPG", "Aventura"], "platform": "Multi"},
    {"name": "Resident Evil 4 Remake", "genres": ["Terror", "Sobrevivência"], "platform": "Multi"},
    {"name": "Dead Space Remake", "genres": ["Terror", "Ficção Científica"], "platform": "Multi"},
    {"name": "Alan Wake 2", "genres": ["Terror Psicológico", "Aventura"], "platform": "Multi"},
    {"name": "Street Fighter 6", "genres": ["Luta", "Competitivo"], "platform": "Multi"},
    {"name": "Tekken 8", "genres": ["Luta", "Ação"], "platform": "Multi"},
    {"name": "Mortal Kombat 1", "genres": ["Luta", "Violência"], "platform": "Multi"},
    {"name": "Forza Horizon 5", "genres": ["Corrida", "Mundo Aberto"], "platform": "Multi"},
    {"name": "Gran Turismo 7", "genres": ["Corrida", "Simulação"], "platform": "PS5"},
    {"name": "F1 23", "genres": ["Corrida", "Simulação"], "platform": "Multi"},
    {"name": "Cities: Skylines II", "genres": ["Simulação", "Construção"], "platform": "PC"},
    {"name": "The Sims 4", "genres": ["Simulação", "Vida"], "platform": "Multi"},
    {"name": "Animal Crossing: New Horizons", "genres": ["Simulação", "Vida"], "platform": "Switch"},
    {"name": "Stardew Valley", "genres": ["RPG", "Simulação", "Fazenda"], "platform": "Multi"},
    {"name": "Hades", "genres": ["Roguelike", "Ação"], "platform": "Multi"},
    {"name": "Dead Cells", "genres": ["Roguelike", "Metroidvania"], "platform": "Multi"},
    {"name": "Returnal", "genres": ["Roguelike", "Tiro"], "platform": "PS5/PC"},
    {"name": "Diablo IV", "genres": ["RPG", "Ação", "Hack-and-slash"], "platform": "Multi"},
    {"name": "Path of Exile", "genres": ["RPG", "Ação", "Gratuito"], "platform": "Multi"},
    {"name": "XCOM 2", "genres": ["Estratégia", "Turno"], "platform": "Multi"},
    {"name": "Civilization VI", "genres": ["Estratégia", "4X"], "platform": "Multi"},
    {"name": "Age of Empires IV", "genres": ["Estratégia em tempo real"], "platform": "PC"},
    {"name": "Total War: Warhammer III", "genres": ["Estratégia", "Tático"], "platform": "PC"},
    {"name": "Football Manager 2024", "genres": ["Simulação", "Esporte"], "platform": "Multi"},
    {"name": "NBA 2K24", "genres": ["Esporte", "Simulação"], "platform": "Multi"},
    {"name": "Madden NFL 24", "genres": ["Esporte", "Futebol Americano"], "platform": "Multi"},
    {"name": "WWE 2K23", "genres": ["Luta", "Esporte"], "platform": "Multi"},
    {"name": "Tony Hawk's Pro Skater 1+2", "genres": ["Esporte", "Skate"], "platform": "Multi"},
    {"name": "Hollow Knight", "genres": ["Metroidvania", "Ação"], "platform": "Multi"},
    {"name": "Ori and the Will of the Wisps", "genres": ["Metroidvania", "Plataforma"], "platform": "Multi"},
    {"name": "Celeste", "genres": ["Plataforma", "Precisão"], "platform": "Multi"},
    {"name": "Cuphead", "genres": ["Plataforma", "Ação"], "platform": "Multi"},
    {"name": "Super Mario Wonder", "genres": ["Plataforma", "Aventura"], "platform": "Switch"},
    {"name": "Sonic Frontiers", "genres": ["Plataforma", "Mundo Aberto"], "platform": "Multi"},
    {"name": "Persona 5 Royal", "genres": ["JRPG", "Social"], "platform": "Multi"},
    {"name": "Final Fantasy XVI", "genres": ["JRPG", "Ação"], "platform": "PS5"},
    {"name": "Dragon Quest XI", "genres": ["JRPG", "Tradicional"], "platform": "Multi"},
    {"name": "Octopath Traveler II", "genres": ["JRPG", "Pixel Art"], "platform": "Multi"},
    {"name": "Kingdom Hearts III", "genres": ["JRPG", "Ação"], "platform": "Multi"},
    {"name": "Nier: Automata", "genres": ["JRPG", "Ação"], "platform": "Multi"},
    {"name": "Darkest Dungeon II", "genres": ["Roguelike", "Estratégia"], "platform": "PC"},
    {"name": "Slay the Spire", "genres": ["Roguelike", "Cartas"], "platform": "Multi"},
    {"name": "Inscryption", "genres": ["Roguelike", "Terror", "Cartas"], "platform": "Multi"},
    {"name": "Vampire Survivors", "genres": ["Roguelite", "Bullet Heaven"], "platform": "Multi"},
    {"name": "Among Us", "genres": ["Party Game", "Social"], "platform": "Multi"},
    {"name": "Fall Guys", "genres": ["Party Game", "Battle Royale"], "platform": "Multi"},
    {"name": "It Takes Two", "genres": ["Co-op", "Aventura"], "platform": "Multi"},
    {"name": "Overcooked 2", "genres": ["Party Game", "Caos"], "platform": "Multi"},
    {"name": "Portal 2", "genres": ["Puzzle", "Co-op"], "platform": "Multi"},
    {"name": "The Witness", "genres": ["Puzzle", "Exploração"], "platform": "Multi"},
    {"name": "Baba Is You", "genres": ["Puzzle", "Lógica"], "platform": "Multi"},
    {"name": "Tetris Effect", "genres": ["Puzzle", "Rítmico"], "platform": "Multi"},
    {"name": "Outer Wilds", "genres": ["Exploração", "Mistério"], "platform": "Multi"},
    {"name": "Subnautica", "genres": ["Sobrevivência", "Exploração"], "platform": "Multi"},
    {"name": "The Forest", "genres": ["Sobrevivência", "Terror"], "platform": "Multi"},
    {"name": "Don't Starve Together", "genres": ["Sobrevivência", "Co-op"], "platform": "Multi"},
    {"name": "Rust", "genres": ["Sobrevivência", "Multiplayer"], "platform": "PC"},
    {"name": "Valheim", "genres": ["Sobrevivência", "Vikings"], "platform": "PC"},
    {"name": "Palworld", "genres": ["Sobrevivência", "Monstros"], "platform": "Multi"},
    {"name": "Lethal Company", "genres": ["Terror", "Co-op"], "platform": "PC"},
    {"name": "Phasmophobia", "genres": ["Terror", "Investigação"], "platform": "PC"},
    {"name": "Amnesia: The Bunker", "genres": ["Terror", "Simulação"], "platform": "Multi"},
    {"name": "Outlast 2", "genres": ["Terror", "Fuga"], "platform": "Multi"},
    {"name": "Dredge", "genres": ["Terror", "Pesca"], "platform": "Multi"},
    {"name": "Dave the Diver", "genres": ["Aventura", "Simulação"], "platform": "Multi"},
    {"name": "Cocoon", "genres": ["Puzzle", "Aventura"], "platform": "Multi"},
    {"name": "Sea of Stars", "genres": ["JRPG", "Retro"], "platform": "Multi"},
    {"name": "Chained Echoes", "genres": ["JRPG", "Pixel Art"], "platform": "Multi"},
    {"name": "Blasphemous 2", "genres": ["Metroidvania", "Souls-like"], "platform": "Multi"},
    {"name": "The Last of Us Part I", "genres": ["Aventura", "Terror"], "platform": "PS5/PC"},
    {"name": "Ghost of Tsushima", "genres": ["Ação", "Mundo Aberto"], "platform": "PS5/PC"},
    {"name": "Horizon Forbidden West", "genres": ["RPG", "Ação"], "platform": "PS5/PC"},
    {"name": "Spider-Man 2", "genres": ["Ação", "Mundo Aberto"], "platform": "PS5"},
    {"name": "Ratchet & Clank: Rift Apart", "genres": ["Plataforma", "Ação"], "platform": "PS5/PC"},
    {"name": "Demon's Souls Remake", "genres": ["RPG", "Souls-like"], "platform": "PS5"},
    {"name": "Bloodborne", "genres": ["RPG", "Terror", "Souls-like"], "platform": "PS4"},
    {"name": "Sekiro: Shadows Die Twice", "genres": ["Ação", "Stealth"], "platform": "Multi"},
    {"name": "Armored Core VI", "genres": ["Ação", "Mechas"], "platform": "Multi"},
    {"name": "Hi-Fi Rush", "genres": ["Rítmico", "Ação"], "platform": "Multi"},
    {"name": "Pentiment", "genres": ["Narrativo", "Histórico"], "platform": "Multi"},
    {"name": "Grounded", "genres": ["Sobrevivência", "Insetos"], "platform": "Multi"},
    {"name": "Sea of Thieves", "genres": ["Aventura", "Pirata"], "platform": "Multi"},
    {"name": "Halo Infinite", "genres": ["FPS", "Ficção Científica"], "platform": "Multi"}
]